# Generated by Django 5.0.7 on 2025-10-10 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ville",
            fields=[
                ("IDVille", models.AutoField(primary_key=True, serialize=False)),
                ("NomVille", models.CharField(max_length=80)),
                ("NomPays", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Voyage",
            fields=[
                ("IDVoyage", models.AutoField(primary_key=True, serialize=False)),
                ("Titre", models.CharField(max_length=120)),
                ("Prix", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Composition",
            fields=[
                ("IDEtape", models.AutoField(primary_key=True, serialize=False)),
                ("nbJours", models.PositiveIntegerField(default=1)),
                (
                    "ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applitravel.ville",
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applitravel.voyage",
                    ),
                ),
            ],
            options={
                "unique_together": {("voyage", "ville")},
            },
        ),
    ]
