# Generated by Django 5.2.7 on 2025-11-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applitravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='image',
            field=models.ImageField(default='imagesVoyages/default.jpg', upload_to='imagesVoyages/'),
        ),
    ]
